#ifndef ENUMS_H
#define ENUMS_H

#define DEBUG

//character classes
enum {WHITESPACE, PUNCTUATION, LETTER, DIGIT, INVALID,PLUS,MINUS,QUOTE,SLASH,AMPERSAND,PIPE,LPARENc,RPARENc,LBRACKETc,RBRACKETc,ASTERISK,PERIODc,SEMICOLONc,COMMAc,COLON,EQUAL,LT,GT,EXCLAIM};

//token types
enum {NUMBER,ID,ADD,SUB,STRING,FUNCTION,BEGIN,END,TYPE,IF,THEN,ELSE,WHILE,CASE,IS,WHEN,DEFAULT,AND,OR,NOT,DIVIDE,COMMENT,BITAND,BITOR,LPAREN,RPAREN,LBRACKET,RBRACKET,PERIOD,COMMA,TIMES,SEMICOLON,ASSIGN,RELOP, EOFMARKER};

//variable types
enum {INTEGERTYPE, BOOLEANTYPE, STRINGTYPE, FUNCTIONTYPE, ARRAYTYPE};


#endif
